-----------------------
-- For Aspectow Appmon
-----------------------

-- Raw event count data (typically 5-minute intervals)
CREATE TABLE IF NOT EXISTS appmon_event_count (
    node_id varchar(50) NOT NULL,
    group_id varchar(50) NOT NULL,
    app_id varchar(50) NOT NULL,
    event_id varchar(50) NOT NULL,
    datetime timestamp NOT NULL,
    total bigint NOT NULL,
    delta bigint NOT NULL,
    error bigint NOT NULL,
    CONSTRAINT appmon_event_count_pk PRIMARY KEY (node_id, app_id, event_id, datetime)
);

CREATE INDEX IF NOT EXISTS appmon_event_count_ix_group ON appmon_event_count (group_id, app_id, event_id, datetime);

COMMENT ON TABLE appmon_event_count IS 'Raw event count data';
COMMENT ON COLUMN appmon_event_count.node_id IS 'Monitoring node identifier';
COMMENT ON COLUMN appmon_event_count.group_id IS 'Monitoring node group identifier';
COMMENT ON COLUMN appmon_event_count.app_id IS 'Application identifier';
COMMENT ON COLUMN appmon_event_count.event_id IS 'Event identifier';
COMMENT ON COLUMN appmon_event_count.datetime IS 'Data point timestamp';
COMMENT ON COLUMN appmon_event_count.total IS 'Cumulative total count (Gauge)';
COMMENT ON COLUMN appmon_event_count.delta IS 'Incremental count for the interval (Counter)';
COMMENT ON COLUMN appmon_event_count.error IS 'Incremental error count for the interval';

-- Hourly aggregated event count data
CREATE TABLE IF NOT EXISTS appmon_event_count_hourly (
    node_id varchar(50) NOT NULL,
    group_id varchar(50) NOT NULL,
    app_id varchar(50) NOT NULL,
    event_id varchar(50) NOT NULL,
    datetime timestamp NOT NULL,
    total bigint NOT NULL,
    delta bigint NOT NULL,
    error bigint NOT NULL,
    CONSTRAINT appmon_event_count_hourly_pk PRIMARY KEY (node_id, app_id, event_id, datetime)
);

CREATE INDEX IF NOT EXISTS appmon_event_count_hourly_ix_group ON appmon_event_count_hourly (group_id, app_id, event_id, datetime);

COMMENT ON TABLE appmon_event_count_hourly IS 'Hourly aggregated event count data';
COMMENT ON COLUMN appmon_event_count_hourly.node_id IS 'Monitoring node identifier';
COMMENT ON COLUMN appmon_event_count_hourly.group_id IS 'Monitoring node group identifier';
COMMENT ON COLUMN appmon_event_count_hourly.app_id IS 'Application identifier';
COMMENT ON COLUMN appmon_event_count_hourly.event_id IS 'Event identifier';
COMMENT ON COLUMN appmon_event_count_hourly.datetime IS 'Hourly truncated timestamp';
COMMENT ON COLUMN appmon_event_count_hourly.total IS 'Cumulative total count at the end of the hour';
COMMENT ON COLUMN appmon_event_count_hourly.delta IS 'Total incremental count for the hour';
COMMENT ON COLUMN appmon_event_count_hourly.error IS 'Total incremental error count for the hour';

-- Most recent event count state for incremental updates
CREATE TABLE IF NOT EXISTS appmon_event_count_last (
    node_id varchar(50) NOT NULL,
    group_id varchar(50) NOT NULL,
    app_id varchar(50) NOT NULL,
    event_id varchar(50) NOT NULL,
    datetime timestamp NOT NULL,
    total bigint NOT NULL,
    delta bigint NOT NULL,
    error bigint NOT NULL,
    reg_dt timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT appmon_event_count_last_pk PRIMARY KEY (node_id, app_id, event_id)
);

CREATE INDEX IF NOT EXISTS appmon_event_count_last_ix_group ON appmon_event_count_last (group_id, app_id, event_id);

COMMENT ON TABLE appmon_event_count_last IS 'Most recent event count state';
COMMENT ON COLUMN appmon_event_count_last.node_id IS 'Monitoring node identifier';
COMMENT ON COLUMN appmon_event_count_last.group_id IS 'Monitoring node group identifier';
COMMENT ON COLUMN appmon_event_count_last.app_id IS 'Application identifier';
COMMENT ON COLUMN appmon_event_count_last.event_id IS 'Event identifier';
COMMENT ON COLUMN appmon_event_count_last.datetime IS 'Last data point timestamp';
COMMENT ON COLUMN appmon_event_count_last.total IS 'Last cumulative total count';
COMMENT ON COLUMN appmon_event_count_last.delta IS 'Last incremental count';
COMMENT ON COLUMN appmon_event_count_last.error IS 'Last incremental error count';
COMMENT ON COLUMN appmon_event_count_last.reg_dt IS 'Database registration timestamp';

------------------------
-- For Aspectow Console
------------------------

-- User accounts
create table if not exists asc_user (
    user_id bigint generated by default as identity primary key,
    username varchar(50) not null unique,
    password varchar(100) not null,
    nickname varchar(50),
    email varchar(100),
    status varchar(10) default 'NORMAL' not null, -- NORMAL, LOCKED, EXPIRED
    allowed_ips varchar(500),
    last_login_at timestamp with time zone,
    created_at timestamp with time zone default current_timestamp not null,
    updated_at timestamp with time zone default current_timestamp not null
);

comment on table asc_user is 'User accounts';

-- Roles
create table if not exists asc_role (
    role_id bigserial not null,
    role_name varchar(50) not null unique,
    description varchar(200),
    primary key (role_id)
);

comment on table asc_role is 'Roles';

-- User-Role mapping
create table if not exists asc_user_role (
    user_id bigint not null,
    role_id bigint not null,
    primary key (user_id, role_id),
    foreign key (user_id) references asc_user(user_id) on delete cascade,
    foreign key (role_id) references asc_role(role_id) on delete cascade
);

comment on table asc_user_role is 'User-Role mapping';

-- Permissions
create table if not exists asc_permission (
    perm_id bigserial not null,
    perm_code varchar(50) not null unique,
    description varchar(200),
    primary key (perm_id)
);

comment on table asc_permission is 'Permissions';

-- Role-Permission mapping
create table if not exists asc_role_permission (
    role_id bigint not null,
    perm_id bigint not null,
    primary key (role_id, perm_id),
    foreign key (role_id) references asc_role(role_id) on delete cascade,
    foreign key (perm_id) references asc_permission(perm_id) on delete cascade
);

comment on table asc_role_permission is 'Role-Permission mapping';

-- Login History
create table if not exists asc_login_history (
    history_id bigserial not null,
    username varchar(50) not null,
    login_at timestamp default current_timestamp not null,
    ip_address varchar(45),
    user_agent varchar(500),
    success_yn char(1) default 'Y' not null,
    primary key (history_id)
);

comment on table asc_login_history is 'Login History';

-- Vault (Encrypted Tokens)
create table if not exists asc_vault (
    vault_id bigserial not null,
    label varchar(100) not null,
    token_type varchar(20) default 'SIMPLE' not null, -- SIMPLE, PERSISTENT, TIME_LIMITED
    encrypted_value varchar(500) not null,
    description varchar(500),
    valid_until timestamp,
    created_at timestamp default current_timestamp not null,
    updated_at timestamp default current_timestamp not null,
    primary key (vault_id)
);

comment on table asc_vault is 'Vault (Encrypted Tokens)';

-- Security Audit Log
create table if not exists asc_audit_log (
    audit_id bigserial not null,
    username varchar(50),
    event_type varchar(50) not null,
    target varchar(100),
    details varchar(1000),
    ip_address varchar(45),
    created_at timestamp default current_timestamp not null,
    primary key (audit_id)
);

comment on table asc_audit_log is 'Security Audit Log';

-- Initial data
insert into asc_role (role_name, description) values ('SUPER_ADMIN', 'Super administrator with full access') on conflict (role_name) do nothing;
insert into asc_role (role_name, description) values ('ADMIN', 'Administrator with limited management access') on conflict (role_name) do nothing;
insert into asc_role (role_name, description) values ('BUILDER', 'Build and deployment engineer') on conflict (role_name) do nothing;
insert into asc_role (role_name, description) values ('VIEWER', 'User with read-only access') on conflict (role_name) do nothing;
insert into asc_role (role_name, description) values ('DEMO', 'Demo user with simulation access') on conflict (role_name) do nothing;

insert into asc_permission (perm_code, description) values ('MONITOR_VIEW', 'Access to monitoring dashboard') on conflict (perm_code) do nothing;
insert into asc_permission (perm_code, description) values ('MONITOR_CONTROL', 'Control monitoring settings') on conflict (perm_code) do nothing;
insert into asc_permission (perm_code, description) values ('USER_MANAGE', 'Manage users and roles') on conflict (perm_code) do nothing;
insert into asc_permission (perm_code, description) values ('NODE_MANAGE', 'Manage and restart cluster nodes') on conflict (perm_code) do nothing;
insert into asc_permission (perm_code, description) values ('COMMAND_EXECUTE', 'Execute remote commands') on conflict (perm_code) do nothing;
insert into asc_permission (perm_code, description) values ('BUILD_VIEW', 'View build and deployment status') on conflict (perm_code) do nothing;
insert into asc_permission (perm_code, description) values ('BUILD_EXECUTE', 'Execute build and deployment scripts') on conflict (perm_code) do nothing;

-- Map permissions to SUPER_ADMIN
insert into asc_role_permission (role_id, perm_id)
select r.role_id, p.perm_id from asc_role r cross join asc_permission p
 where r.role_name = 'SUPER_ADMIN'
on conflict (role_id, perm_id) do nothing;

-- Map permissions to ADMIN
insert into asc_role_permission (role_id, perm_id)
select r.role_id, p.perm_id from asc_role r cross join asc_permission p
 where r.role_name = 'ADMIN' and p.perm_code in ('MONITOR_VIEW', 'COMMAND_EXECUTE', 'NODE_MANAGE', 'BUILD_VIEW', 'BUILD_EXECUTE')
on conflict (role_id, perm_id) do nothing;

-- Map permissions to BUILDER
insert into asc_role_permission (role_id, perm_id)
select r.role_id, p.perm_id from asc_role r cross join asc_permission p
 where r.role_name = 'BUILDER' and p.perm_code in ('BUILD_VIEW', 'BUILD_EXECUTE')
on conflict (role_id, perm_id) do nothing;

-- Map permissions to VIEWER
insert into asc_role_permission (role_id, perm_id)
select r.role_id, p.perm_id from asc_role r cross join asc_permission p
 where r.role_name = 'VIEWER' and p.perm_code in ('MONITOR_VIEW', 'BUILD_VIEW')
on conflict (role_id, perm_id) do nothing;

-- Map permissions to DEMO
insert into asc_role_permission (role_id, perm_id)
select r.role_id, p.perm_id from asc_role r cross join asc_permission p
 where r.role_name = 'DEMO'
on conflict (role_id, perm_id) do nothing;

-- Initial Super Admin user (password: admin123)
insert into asc_user (username, password, nickname, email) values ('admin', 'admin123', 'Super Admin', 'admin@aspectow.com') on conflict (username) do nothing;
insert into asc_user_role (user_id, role_id)
select u.user_id, r.role_id from asc_user u, asc_role r where u.username = 'admin' and r.role_name = 'SUPER_ADMIN'
on conflict (user_id, role_id) do nothing;
