driver=org.h2.Driver
url=jdbc:h2:%{aspectow.console.config.db.h2.path:~/aspectow-console};MODE=MariaDB;DB_CLOSE_DELAY=-1;TRACE_LEVEL_FILE=0;INIT=RUNSCRIPT FROM 'classpath:com/aspectran/aspectow/console/config/db/aspectow-console-creation.sql'
username=sa
password=
