-----------------------
-- For Aspectow Appmon
-----------------------

-- Raw event count data (typically 5-minute intervals)
create table appmon_event_count (
    node_id varchar(50) not null,
    group_id varchar(50) not null,
    app_id varchar(50) not null,
    event_id varchar(50) not null,
    datetime date not null,
    total integer not null,
    delta integer not null,
    error integer not null,
    constraint appmon_event_count_pk primary key (node_id, app_id, event_id, datetime)
);

create index appmon_event_count_ix_group on appmon_event_count (group_id, app_id, event_id, datetime);

comment on table appmon_event_count is 'Raw event count data';
comment on column appmon_event_count.node_id is 'Monitoring node identifier';
comment on column appmon_event_count.group_id is 'Monitoring node group identifier';
comment on column appmon_event_count.app_id is 'Application identifier';
comment on column appmon_event_count.event_id is 'Event identifier';
comment on column appmon_event_count.datetime is 'Data point timestamp';
comment on column appmon_event_count.total is 'Cumulative total count (Gauge)';
comment on column appmon_event_count.delta is 'Incremental count for the interval (Counter)';
comment on column appmon_event_count.error is 'Incremental error count for the interval';

-- Hourly aggregated event count data
create table appmon_event_count_hourly (
    node_id varchar(50) not null,
    group_id varchar(50) not null,
    app_id varchar(50) not null,
    event_id varchar(50) not null,
    datetime date not null,
    total integer not null,
    delta integer not null,
    error integer not null,
    constraint appmon_event_count_hourly_pk primary key (node_id, app_id, event_id, datetime)
);

create index appmon_event_count_hourly_ix_group on appmon_event_count_hourly (group_id, app_id, event_id, datetime);

comment on table appmon_event_count_hourly is 'Hourly aggregated event count data';
comment on column appmon_event_count_hourly.node_id is 'Monitoring node identifier';
comment on column appmon_event_count_hourly.group_id is 'Monitoring node group identifier';
comment on column appmon_event_count_hourly.app_id is 'Application identifier';
comment on column appmon_event_count_hourly.event_id is 'Event identifier';
comment on column appmon_event_count_hourly.datetime is 'Hourly truncated timestamp';
comment on column appmon_event_count_hourly.total is 'Cumulative total count at the end of the hour';
comment on column appmon_event_count_hourly.delta is 'Total incremental count for the hour';
comment on column appmon_event_count_hourly.error is 'Total incremental error count for the hour';

-- Most recent event count state for incremental updates
create table appmon_event_count_last (
    node_id varchar(50) not null,
    group_id varchar(50) not null,
    app_id varchar(50) not null,
    event_id varchar(50) not null,
    datetime date not null,
    total integer not null,
    delta integer not null,
    error integer not null,
    reg_dt date default sysdate not null,
    constraint appmon_event_count_last_pk primary key (node_id, app_id, event_id)
);

create index appmon_event_count_last_ix_group on appmon_event_count_last (group_id, app_id, event_id);

comment on table appmon_event_count_last is 'Most recent event count state';
comment on column appmon_event_count_last.node_id is 'Monitoring node identifier';
comment on column appmon_event_count_last.group_id is 'Monitoring node group identifier';
comment on column appmon_event_count_last.app_id is 'Application identifier';
comment on column appmon_event_count_last.event_id is 'Event identifier';
comment on column appmon_event_count_last.datetime is 'Last data point timestamp';
comment on column appmon_event_count_last.total is 'Last cumulative total count';
comment on column appmon_event_count_last.delta is 'Last incremental count';
comment on column appmon_event_count_last.error is 'Last incremental error count';
comment on column appmon_event_count_last.reg_dt is 'Database registration timestamp';

------------------------
-- For Aspectow Console
------------------------

-- User accounts
CREATE TABLE asc_user (
    user_id NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL UNIQUE,
    password VARCHAR2(100) NOT NULL,
    nickname VARCHAR2(50),
    email VARCHAR2(100),
    status VARCHAR2(10) DEFAULT 'NORMAL' NOT NULL,
    allowed_ips VARCHAR2(500),
    last_login_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON TABLE asc_user IS 'User accounts';

-- Roles
CREATE TABLE asc_role (
    role_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    role_name VARCHAR2(50) NOT NULL UNIQUE,
    description VARCHAR2(200),
    PRIMARY KEY (role_id)
);

COMMENT ON TABLE asc_role IS 'Roles';

-- User-Role mapping
CREATE TABLE asc_user_role (
    user_id NUMBER(19) NOT NULL,
    role_id NUMBER(19) NOT NULL,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES asc_user(user_id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES asc_role(role_id) ON DELETE CASCADE
);

COMMENT ON TABLE asc_user_role IS 'User-Role mapping';

-- Permissions
CREATE TABLE asc_permission (
    perm_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    perm_code VARCHAR2(50) NOT NULL UNIQUE,
    description VARCHAR2(200),
    PRIMARY KEY (perm_id)
);

COMMENT ON TABLE asc_permission IS 'Permissions';

-- Role-Permission mapping
CREATE TABLE asc_role_permission (
    role_id NUMBER(19) NOT NULL,
    perm_id NUMBER(19) NOT NULL,
    PRIMARY KEY (role_id, perm_id),
    FOREIGN KEY (role_id) REFERENCES asc_role(role_id) ON DELETE CASCADE,
    FOREIGN KEY (perm_id) REFERENCES asc_permission(perm_id) ON DELETE CASCADE
);

COMMENT ON TABLE asc_role_permission IS 'Role-Permission mapping';

-- Login History
CREATE TABLE asc_login_history (
    history_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR2(50) NOT NULL,
    login_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ip_address VARCHAR2(45),
    user_agent VARCHAR2(500),
    success_yn CHAR(1) DEFAULT 'Y' NOT NULL,
    PRIMARY KEY (history_id)
);

COMMENT ON TABLE asc_login_history IS 'Login History';

-- Vault (Encrypted Tokens)
CREATE TABLE asc_vault (
    vault_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR2(100) NOT NULL,
    token_type VARCHAR2(20) DEFAULT 'SIMPLE' NOT NULL,
    encrypted_value VARCHAR2(500) NOT NULL,
    description VARCHAR2(500),
    valid_until TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (vault_id)
);

COMMENT ON TABLE asc_vault IS 'Vault (Encrypted Tokens)';

-- Security Audit Log
CREATE TABLE asc_audit_log (
    audit_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR2(50),
    event_type VARCHAR2(50) NOT NULL,
    target VARCHAR2(100),
    details VARCHAR2(1000),
    ip_address VARCHAR2(45),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (audit_id)
);

COMMENT ON TABLE asc_audit_log IS 'Security Audit Log';

-- Initial data
MERGE INTO asc_role a USING (SELECT 'SUPER_ADMIN' role_name, 'Super administrator with full access' description FROM dual) b ON (a.role_name = b.role_name) WHEN NOT MATCHED THEN INSERT (role_name, description) VALUES (b.role_name, b.description);
MERGE INTO asc_role a USING (SELECT 'ADMIN' role_name, 'Administrator with limited management access' description FROM dual) b ON (a.role_name = b.role_name) WHEN NOT MATCHED THEN INSERT (role_name, description) VALUES (b.role_name, b.description);
MERGE INTO asc_role a USING (SELECT 'BUILDER' role_name, 'Build and deployment engineer' description FROM dual) b ON (a.role_name = b.role_name) WHEN NOT MATCHED THEN INSERT (role_name, description) VALUES (b.role_name, b.description);
MERGE INTO asc_role a USING (SELECT 'VIEWER' role_name, 'User with read-only access' description FROM dual) b ON (a.role_name = b.role_name) WHEN NOT MATCHED THEN INSERT (role_name, description) VALUES (b.role_name, b.description);
MERGE INTO asc_role a USING (SELECT 'DEMO' role_name, 'Demo user with simulation access' description FROM dual) b ON (a.role_name = b.role_name) WHEN NOT MATCHED THEN INSERT (role_name, description) VALUES (b.role_name, b.description);

MERGE INTO asc_permission a USING (SELECT 'MONITOR_VIEW' perm_code, 'Access to monitoring dashboard' description FROM dual) b ON (a.perm_code = b.perm_code) WHEN NOT MATCHED THEN INSERT (perm_code, description) VALUES (b.perm_code, b.description);
MERGE INTO asc_permission a USING (SELECT 'MONITOR_CONTROL' perm_code, 'Control monitoring settings' description FROM dual) b ON (a.perm_code = b.perm_code) WHEN NOT MATCHED THEN INSERT (perm_code, description) VALUES (b.perm_code, b.description);
MERGE INTO asc_permission a USING (SELECT 'USER_MANAGE' perm_code, 'Manage users and roles' description FROM dual) b ON (a.perm_code = b.perm_code) WHEN NOT MATCHED THEN INSERT (perm_code, description) VALUES (b.perm_code, b.description);
MERGE INTO asc_permission a USING (SELECT 'NODE_MANAGE' perm_code, 'Manage and restart cluster nodes' description FROM dual) b ON (a.perm_code = b.perm_code) WHEN NOT MATCHED THEN INSERT (perm_code, description) VALUES (b.perm_code, b.description);
MERGE INTO asc_permission a USING (SELECT 'COMMAND_EXECUTE' perm_code, 'Execute remote commands' description FROM dual) b ON (a.perm_code = b.perm_code) WHEN NOT MATCHED THEN INSERT (perm_code, description) VALUES (b.perm_code, b.description);
MERGE INTO asc_permission a USING (SELECT 'BUILD_VIEW' perm_code, 'View build and deployment status' description FROM dual) b ON (a.perm_code = b.perm_code) WHEN NOT MATCHED THEN INSERT (perm_code, description) VALUES (b.perm_code, b.description);
MERGE INTO asc_permission a USING (SELECT 'BUILD_EXECUTE' perm_code, 'Execute build and deployment scripts' description FROM dual) b ON (a.perm_code = b.perm_code) WHEN NOT MATCHED THEN INSERT (perm_code, description) VALUES (b.perm_code, b.description);

-- Map permissions to SUPER_ADMIN
MERGE INTO asc_role_permission a USING (
    SELECT r.role_id, p.perm_id
      FROM asc_role r
     CROSS JOIN asc_permission p
     WHERE r.role_name = 'SUPER_ADMIN'
) b ON (a.role_id = b.role_id AND a.perm_id = b.perm_id) WHEN NOT MATCHED THEN INSERT (role_id, perm_id) VALUES (b.role_id, b.perm_id);

-- Map permissions to ADMIN
MERGE INTO asc_role_permission a USING (
    SELECT r.role_id, p.perm_id
      FROM asc_role r
     CROSS JOIN asc_permission p
     WHERE r.role_name = 'ADMIN'
       AND p.perm_code IN ('MONITOR_VIEW', 'COMMAND_EXECUTE', 'NODE_MANAGE', 'BUILD_VIEW', 'BUILD_EXECUTE')
) b ON (a.role_id = b.role_id AND a.perm_id = b.perm_id) WHEN NOT MATCHED THEN INSERT (role_id, perm_id) VALUES (b.role_id, b.perm_id);

-- Map permissions to BUILDER
MERGE INTO asc_role_permission a USING (
    SELECT r.role_id, p.perm_id
      FROM asc_role r
     CROSS JOIN asc_permission p
     WHERE r.role_name = 'BUILDER'
       AND p.perm_code IN ('BUILD_VIEW', 'BUILD_EXECUTE')
) b ON (a.role_id = b.role_id AND a.perm_id = b.perm_id) WHEN NOT MATCHED THEN INSERT (role_id, perm_id) VALUES (b.role_id, b.perm_id);

-- Map permissions to VIEWER
MERGE INTO asc_role_permission a USING (
    SELECT r.role_id, p.perm_id
      FROM asc_role r
     CROSS JOIN asc_permission p
     WHERE r.role_name = 'VIEWER'
       AND p.perm_code IN ('MONITOR_VIEW', 'BUILD_VIEW')
) b ON (a.role_id = b.role_id AND a.perm_id = b.perm_id) WHEN NOT MATCHED THEN INSERT (role_id, perm_id) VALUES (b.role_id, b.perm_id);

-- Map permissions to DEMO
MERGE INTO asc_role_permission a USING (
    SELECT r.role_id, p.perm_id
      FROM asc_role r
     CROSS JOIN asc_permission p
     WHERE r.role_name = 'DEMO'
) b ON (a.role_id = b.role_id AND a.perm_id = b.perm_id) WHEN NOT MATCHED THEN INSERT (role_id, perm_id) VALUES (b.role_id, b.perm_id);

-- Initial Super Admin user (password: admin123)
MERGE INTO asc_user a USING (SELECT 'admin' username, 'admin123' password, 'Super Admin' nickname, 'admin@aspectow.com' email FROM dual) b ON (a.username = b.username) WHEN NOT MATCHED THEN INSERT (username, password, nickname, email) VALUES (b.username, b.password, b.nickname, b.email);
MERGE INTO asc_user_role a USING (
    SELECT u.user_id, r.role_id
      FROM asc_user u
     CROSS JOIN asc_role r
     WHERE u.username = 'admin' AND r.role_name = 'SUPER_ADMIN'
) b ON (a.user_id = b.user_id AND a.role_id = b.role_id) WHEN NOT MATCHED THEN INSERT (user_id, role_id) VALUES (b.user_id, b.role_id);
