# ==============================================================================
# Application Installation and Execution Configuration
# ==============================================================================
# This file is sourced by setup scripts to configure deployment and runtime
# variables.

# The name of the application. Used for directory names and service names.
APP_NAME="aspectow-console-demo"

# The Git repository URL for the application source code.
REPO_URL="https://github.com/aspectran/aspectow"

# The Linux user and group that the daemon service will run as.
DAEMON_USER="aspectran"
DAEMON_GROUP="aspectran"

# The root directory for the application installation.
BASE_DIR="."

# A temporary directory for cloning and building the application from source.
BUILD_DIR="$BASE_DIR/.build"

# The path to the cloned Git repository within the build directory.
REPO_DIR="$BUILD_DIR/$APP_NAME/"

# The directory where the runnable application files will be deployed.
# This is the application's runtime home.
DEPLOY_DIR="$BASE_DIR/app"

# A directory for backing up the previous version during an update.
RESTORE_DIR="$BASE_DIR/app-restore"

# The process name for the daemon.
PROC_NAME="$APP_NAME"

export JAVA_TOOL_OPTIONS="--enable-native-access=ALL-UNNAMED"

# Java system properties to be passed to the Aspectran application at runtime.
# Use this to set active profiles, configuration paths, etc.
# The 'export' command makes this variable available to all child processes.
ASPECTRAN_OPTS="
-Duser.timezone=UTC
-Daspectran.profiles.active=dev,gateway,console.ui
-Daspectran.profiles.base.console=dev,h2,console.custom-ui
-Daspectran.workPath=./app/work
-Daspectran.tempPath=./app/temp
-Daspectran.commandsPath=./app/cmd
-Daspectran.logsDir=./app/logs
-Daspectow.node.id=dev-console-node1
-Daspectow.node.console=true
-Dtow.server.listener.http.port=8082
-Dtow.context.root.session.cookieName=JSESSIONID-8082
-Dtow.context.console.session.cookieName=JSESSIONID-8082
-Daspectow.console.config.db.h2.path_explicit=~/aspectow-console-demo
"
export ASPECTRAN_OPTS="$ASPECTRAN_OPTS"
