name: Sonatype
on:
  push:
    branches:
      - master
jobs:
  deploy:
    if: github.repository_owner == 'aspectran' && !contains(toJSON(github.event.head_commit.message), '[maven-release-plugin]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: 'maven'
          server-id: central
          server-username: CENTRAL_USERNAME # env variable for username in deploy
          server-password: CENTRAL_PASSWORD # env variable for token in deploy
          gpg-private-key: "${{ secrets.GPG_SIGNING_KEY }}"
          overwrite-settings: false
      - name: Deploy snapshot artifacts
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
        run: mvn deploy -B -V -U -ntp --batch-mode --settings .mvn/settings.xml -Dpgp.keyname=${{ secrets.GPG_KEY_NAME }} -DskipTests=true -D"license.skip=true" -Prelease
